"""empty message

Revision ID: 434fb4dd2ed4
Revises: 97e9b20ec558
Create Date: 2023-10-25 19:05:01.011265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434fb4dd2ed4'
down_revision = '97e9b20ec558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=180),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=180),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
