"""empty message

Revision ID: 75d9125798b8
Revises: f02c1394d44a
Create Date: 2023-11-09 17:50:24.570479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d9125798b8'
down_revision = 'f02c1394d44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=4000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
