"""empty message

Revision ID: 8883fd6a5884
Revises: 5c03b23e5736
Create Date: 2023-11-14 00:30:57.317222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8883fd6a5884'
down_revision = '5c03b23e5736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('lng', sa.String(length=200), nullable=False))
        batch_op.drop_column('coordinates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
