"""empty message

Revision ID: 939c56c0aaf4
Revises: 346e5bf69b60
Create Date: 2023-10-30 16:25:28.757569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939c56c0aaf4'
down_revision = '346e5bf69b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
